# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint_1.xdc

# Block Designs: bd/ADD8bit1/ADD8bit1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD8bit1 || ORIG_REF_NAME==ADD8bit1} -quiet] -quiet

# IP: bd/ADD8bit1/ip/ADD8bit1_ADD1_0_0/ADD8bit1_ADD1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD8bit1_ADD1_0_0 || ORIG_REF_NAME==ADD8bit1_ADD1_0_0} -quiet] -quiet

# IP: bd/ADD8bit1/ip/ADD8bit1_ADD1_0_1/ADD8bit1_ADD1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD8bit1_ADD1_0_1 || ORIG_REF_NAME==ADD8bit1_ADD1_0_1} -quiet] -quiet

# IP: bd/ADD8bit1/ip/ADD8bit1_ADD1_0_2/ADD8bit1_ADD1_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD8bit1_ADD1_0_2 || ORIG_REF_NAME==ADD8bit1_ADD1_0_2} -quiet] -quiet

# IP: bd/ADD8bit1/ip/ADD8bit1_ADD1_0_3/ADD8bit1_ADD1_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD8bit1_ADD1_0_3 || ORIG_REF_NAME==ADD8bit1_ADD1_0_3} -quiet] -quiet

# IP: bd/ADD8bit1/ip/ADD8bit1_ADD1_0_4/ADD8bit1_ADD1_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD8bit1_ADD1_0_4 || ORIG_REF_NAME==ADD8bit1_ADD1_0_4} -quiet] -quiet

# IP: bd/ADD8bit1/ip/ADD8bit1_ADD1_0_5/ADD8bit1_ADD1_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD8bit1_ADD1_0_5 || ORIG_REF_NAME==ADD8bit1_ADD1_0_5} -quiet] -quiet

# IP: bd/ADD8bit1/ip/ADD8bit1_ADD1_0_6/ADD8bit1_ADD1_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD8bit1_ADD1_0_6 || ORIG_REF_NAME==ADD8bit1_ADD1_0_6} -quiet] -quiet

# IP: bd/ADD8bit1/ip/ADD8bit1_ADD1_0_7/ADD8bit1_ADD1_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADD8bit1_ADD1_0_7 || ORIG_REF_NAME==ADD8bit1_ADD1_0_7} -quiet] -quiet

# XDC: bd/ADD8bit1/ADD8bit1_ooc.xdc
