# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ConstraintsBCD.xdc

# Block Designs: bd/CONTADOR_BCD/CONTADOR_BCD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CONTADOR_BCD || ORIG_REF_NAME==CONTADOR_BCD} -quiet] -quiet

# IP: bd/CONTADOR_BCD/ip/CONTADOR_BCD_COUNTER_E_0_0/CONTADOR_BCD_COUNTER_E_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CONTADOR_BCD_COUNTER_E_0_0 || ORIG_REF_NAME==CONTADOR_BCD_COUNTER_E_0_0} -quiet] -quiet

# IP: bd/CONTADOR_BCD/ip/CONTADOR_BCD_DIV1HZ_0_0/CONTADOR_BCD_DIV1HZ_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CONTADOR_BCD_DIV1HZ_0_0 || ORIG_REF_NAME==CONTADOR_BCD_DIV1HZ_0_0} -quiet] -quiet

# IP: bd/CONTADOR_BCD/ip/CONTADOR_BCD_DEC1_BINARIO_SSD_0_0/CONTADOR_BCD_DEC1_BINARIO_SSD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CONTADOR_BCD_DEC1_BINARIO_SSD_0_0 || ORIG_REF_NAME==CONTADOR_BCD_DEC1_BINARIO_SSD_0_0} -quiet] -quiet

# IP: bd/CONTADOR_BCD/ip/CONTADOR_BCD_DEMUX_0_0/CONTADOR_BCD_DEMUX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CONTADOR_BCD_DEMUX_0_0 || ORIG_REF_NAME==CONTADOR_BCD_DEMUX_0_0} -quiet] -quiet

# XDC: bd/CONTADOR_BCD/CONTADOR_BCD_ooc.xdc
